### ISSUE TITLE
baseline-resnet50_dilated8-c1_bilinear_deepsup has no pre-trained models

### ISSUE THREAD

**Issue by jianchao-li** [CSAILVision/semantic-segmentation-pytorch#116] opened 2018-10-08 11:01 UTC
Hello, thank you for sharing this nice repo.

I visited [baseline-resnet50_dilated8-c1_bilinear_deepsup](http://sceneparsing.csail.mit.edu/model/pytorch/baseline-resnet50_dilated8-c1_bilinear_deepsup/) and I found there was nothing in this folder. Are the pre-trained models accidentally missing here? Or, is it supposed to be so?

**Comment by svjack** [comment] 2019-03-30 11:07
You can use encoder and decoder in http://sceneparsing.csail.mit.edu/model/pytorch/baseline-resnet50-upernet/ and edit opts as
 python -u test.py --model_path C:\Coding\Python\segmentation\baseline-resnet50_dilated8-ppm_bilinear_deepsup --test_img ADE_val_00001519.jpg --arch_encoder resnet50 --arch_decoder upernet --fc_dim 2048 --result C:\Coding\Python\segmentation\result

to run the test demo !

**Comment by hangzhaomit** [comment] 2019-07-24 20:59
Hope the problem is solved, I will close this for now.

**Closed by hangzhaomit** 2019-07-24 20:59 UTC
